const searchInput = document.getElementById('search');
const glossary = document.getElementById('glossary');

// Array de objetos com os termos do glossário (substitua por seus dados)
const terms = [
  { term: ' 	1.  Altcoin	', definition: '	 Criptomoeda alternativa, criada após o Bitcoin. 	' } ,
  { term: ' 	2.  Ataque de 51%	', definition: '	" Um ataque de 51% pode ser executado contra rede blockchain que utiliza o algoritmo de consenso PoW, no qual uma única entidade ou organização consegue controlar a maioria do hashrate, podendo causar e explorar falhas no sistema. O atacante teria os seguintes poderes	 poder de mineração suficiente para excluir ou modificar a ordem das transações de forma intencional; fazer retroceder transações, o que poderia acarretar um problema de double-spending (gasto duplo); o fraudador pode impedir que algumas ou todas as transações sejam confirmadas (processo conhecido como ataque de negação de serviço) ou impedir que alguns ou todos os mineradores continuem seu trabalho, monopolizando mineração. O atacante não pode	 reverter transações de outros usuários ou impedir que novas transações sejam criadas e transmitidas à rede; criar moedas do nada; mudar a recompensa dos blocos; ou roubar moedas que nunca lhe pertenceram. "	' } ,
  { term: ' 	3.  AT (Análise técnica)	', definition: '	 Análise Técnica é uma ferramenta utilizada tanto por especuladores profissionais, como por amadores para análise do movimento de preço de alguns ativos financeiros, com base na oferta e procura destes. 	' } ,
  { term: ' 	4.  AML (Anti Money Laundering – Antilavagem de Dinheiro)	', definition: '	 É um termo que se refere às regulamentações impostas em uma indústria financeira, em um esforço para prevenir e deter atividades ilegais. A lavagem de dinheiro indica ocultar a origem dos fundos. Diferentes jurisdições usam diferentes leis de AML para garantir que dinheiro “sujo” não seja recolocado no sistema. 	' } ,
  { term: ' 	5.  Alavancagem (leverage)	', definition: '	 É uma estratégia de investimento que usa dinheiro emprestado – especificamente, o uso de vários instrumentos financeiros ou capital emprestado – para aumentar o potencial retorno de um investimento. 	' } ,
  { term: ' 	6.  Algoritmos	', definition: '	 Um algoritmo é uma sequência finita de ações executáveis que visam obter uma solução para um determinado tipo de problema. 	' } ,
  { term: ' 	7.  Arbitragem (arbitrage)	', definition: '	 É a compra e venda de um ativo para lucrar com uma diferença no preço entre mercados. É uma operação que lucra explorando as diferenças de preço de instrumentos financeiros idênticos ou similares em diferentes mercados ou de diferentes formas. A arbitragem existe como resultado de ineficiências do mercado e, portanto, não existiria se todos os mercados fossem perfeitamente eficientes. 	' } ,
  { term: ' 	8.  Antifrágeis	', definition: '	" Coisas que se beneficiam com o caos. A antifragilidade, um neologismo proposto por Taleb, seria o exato oposto da fragilidade, estando além da resiliência ou da robustez. O resiliente resiste a choques e ao tempo e permanece o mesmo, o antifrágil fica melhor. Esta propriedade estaria por trás de muitas coisas que mudaram com o tempo	 desde ideias até mesmo a própria existência do ser humano como espécie. 	"	' } ,
  { term: ' 	9.  ASIC	', definition: '	 Acrônimo de "Application Specific Integrated Circuit" (Circuito Integrado de Aplicação Específica), é um chip criado especificamente para realizar uma tarefa. No caso do Bitcoin, os ASICs foram criados para processar hash SHA-256 e minerar blocos com maior eficiência. 	' } ,
  { term: ' 	10.  Ancapistão	', definition: '	 É uma sociedade em que não existe a figura do Estado e os indivíduos podem escolher a qual tipo de governança desejam se submeter. O respeito à propriedade privada e ao livre mercado é a prioridade; serviços como educação, saúde, segurança (pública e privada), tribunais seriam fornecidos por concorrentes privados em vez de coercitivamente pelo Estado. 	' } ,
  { term: ' 	11.  Bail-in (Resgate interno)	', definition: '	 Quando o dinheiro do depositante (sócio ou credor) é usado para tratar a má saúde financeira dos bancos. Por exemplo, quando a Bitfinex hackeada alegava não ter bitcoins para quitar todos os saldos na plataforma e descontou valores dos saldos sacados até a sua recuperação. 	' } ,
  { term: ' 	12.  Bail-out (Resgate externo)	', definition: '	 Quando o recurso externo normalmente “dinheiro público”, é usado para tratar a precária saúde financeira de uma instituição financeira à beira da falência. O governo simplesmente dá dinheiro (na forma de empréstimos, títulos e até em dinheiro) ao banco enfermo para sua sobrevivência. 	' } ,
  { term: ' 	13.  Backwardation	', definition: '	 ocorre quando o preço futuro é menor do que o preço à vista (spot), quando é possível fazer renda fixa em BTC vendendo presente e comprando o futuro. Situação oposta ao contango, em que o valor futuro é maior que o spot e é possível fazer cash and carry, consolidando renda fixa em dólar. 	' } ,
  { term: ' 	14.  Betting (Aposta)	', definition: '	 É a ação de apostar dinheiro, bens, tempo ou qualquer outra coisa no resultado de algo, como um jogo ou corrida. Em outras palavras, o ato ou prática de jogar jogos de azar para uma aposta; geralmente em dinheiro. 	' } ,
  { term: ' 	15.  Bit	', definition: '	 É uma unidade comum para designar uma subunidade de bitcoin – 1.000.000 de bits é igual a 1 bitcoin. Esta unidade é geralmente mais conveniente para colocar preços em gorjetas, produtos e serviços. 	' } ,
  { term: ' 	16.  Bimetalismo	', definition: '	 É o termo econômico para um padrão monetário em que o valor da unidade monetária é definido como equivalente a determinadas quantidades de dois metais, tipicamente ouro e prata, criando uma taxa fixa de troca entre eles. 	' } ,
  { term: ' 	17.  BIP (Bitcoin Improvement Proposal)	', definition: '	 Proposta de melhoria do Bitcoin é um documento para a introdução de recursos ou informações no Bitcoin. O BIP deve fornecer uma especificação técnica concisa do atributo e uma justificativa para a nova proposta de recurso. Esta é a maneira padrão de comunicar ideias, já que o Bitcoin não tem estrutura formal de organização. O primeiro BIP (BIP 0001) foi enviado por Amir Taaki em 19/08/2011 e descreveu o que é um BIP. 	' } ,
  { term: ' 	18.  Bitcoin/bitcoin – Bitcoin	', definition: '	 Quando grafado em letra maiúscula inicial, é usado para descrever o conceito do sistema ou a rede completa (software e hardware); bitcoin – em letra minúscula – é usado para descrever a unidade básica com a qual rede denomina movimentação e saldo em contas. É a moeda virtual mundial desenvolvida em código aberto e estrutura descentralizada e difundida pela Internet por indivíduo ou grupo utilizando o pseudônimo “Satoshi Nakamoto". Todas as transações realizadas são armazenadas em um banco de dados on-line e seus símbolos são ฿, BTC ou XBT. Atualmente, a menor fração do bitcoin é o centésimo milionésimo, denominado satoshi. 	' } ,
  { term: ' 	19.  Bloco (block)	', definition: '	 Um bloco é um registro dentro da blockchain que contém e confirma várias transações em espera na mempool. Aproximadamente a cada 10 minutos, em média, um novo bloco com transações é anexado à blockchain por meio do processo de mineração. 	' } ,
  { term: ' 	20.  Blockchain	', definition: '	 A blockchain é um registro público de transações Bitcoin em ordem cronológica. A blockchain é compartilhada entre todos os usuários do Bitcoin. É usada para verificar o registro e a validade de transações Bitcoin e impedir gasto duplo. 	' } ,
  { term: ' 	21.  Block reward (Recompensa de bloco)	', definition: '	 Refere-se aos novos bitcoins concedidos pela rede Bitcoin aos seus mineradores elegíveis para cada bloco minerado com sucesso. Decai em 50% a cada 210.000 blocos, pelo mecanismo chamado halving ou halvening. 	' } ,
  { term: ' 	22.  Burocracia virtual	', definition: '	 Conceito cunhado por Olavo de Carvalho para a classe de indivíduos preparados para ocupar cargos na Administração, mas sem função, “seu único lugar possível na sociedade é no Estado, mas o Estado não tem lugar para eles”. Este grupo se diferencia da “geração nemnem” pela expectativa específica de ingressar em postos do serviço público e é, em grande parte, explicado pelo “educacionismo”[450] . São rejeitados, inativos economicamente, que servem de idiotas úteis no conceito clássico leninista, defendendo interesses de burocratas apenas pela esperança de ocupar algum dia este papel. 	' } ,
  { term: ' 	23.  Captura Administrativa (ou conhecida por Teoria da Captura)	', definition: '	 É um ponto fundamental do ramo da teoria da escolha pública conhecido como regulação econômica. A captura administrativa é uma forma de corrupção política que ocorre quando uma agência reguladora, criada para agir de acordo com o “interesse público”, age em benefício de interesses comerciais ou políticos de específicos grupos de interesse que dominam a indústria ou o setor daquela agência reguladora. A captura do regulador é uma forma de falha do Estado ao criar brecha para firmas ou grupos políticos atuarem de maneira prejudicial ao público, ou seja, produzindo externalidades negativas. Os órgãos são ditos “agências capturadas”. 	' } ,
  { term: ' 	24.  Carteira (wallet)	', definition: '	 A carteira Bitcoin é o equivalente a um cofre ou carteira no mundo “legacy” que contém suas chaves privadas e permite que você gaste seus bitcoins efetivamente enviando-os a um novo endereço, geralmente do recebedor. 	' } ,
  { term: ' 	25.  CBDC (Central Bank Digital Currency)	', definition: '	" são moedas digitais emitidas por bancos centrais, sejam atreladas a uma moeda fiduciária (Yuan digital) ou stable Commodity (Petro Venezuelano). São uma etapa para eliminação de moeda alodial (numerário em espécie) e aumento de poderes estatais para aumentar base monetária, maximizando a) efeito das reservas fracionárias (vez que TODOS os valores estarão depositados em alguma instituição); b) controle estatal (tanto de informação de quem transaciona com quem, como no poder de congelar ou invalidar saldos ou transações); c) capacidade de endividamento dos governos, impossibilitando a elisão ao juro negativo com saque em numerário; e, d) capacidade de políticas de “estímulos ao consumo”, com créditos com expiração para uso, como vouchers (dinheiro programável). O PIX é uma etapa para a implantação da CBDC, reduzindo brutalmente privacidade dos usuários em troca de transações mais rápidas e “grátis” – e usam várias soluções comuns em criptos, como pagamentos por QRcode. O BCB promete desenvolver soluções de smart contracts e até reais digitais offline (como smartcard usado em transportes). "	' } ,
  { term: ' 	26.  Chave pública (Public key)	', definition: '	 Um conjunto de números e letras derivado matematicamente de uma chave privada. Você pode compartilhar sua chave pública para poder receber mensagens (com bitcoins) de outros usuários na rede. 	' } ,
  { term: ' 	27.  Chave privada (Private key)	', definition: '	 Uma chave privada é um também conjunto de números e letras, uma combinação única de bytes de informação utilizada para assinar transações. Pense na chave privada como uma senha muito forte. As chaves privadas não devem ser compartilhadas jamais. Qualquer pessoa em posse da sua chave privada pode assinar transações e transferir a posse de seus bitcoins para outra chave privada. 	' } ,
  { term: ' 	28.  Cypherpunks	', definition: '	 É um grupo informal de pessoas interessadas em criptografia e privacidade. 	' } ,
  { term: ' 	29.  Cold storage (Armazenamento a Frio)	', definition: '	 É uma carteira off-line usada para armazenar bitcoins. Com o armazenamento a frio, a carteira digital é armazenada em uma plataforma que não está conectada à Internet, protegendo a carteira contra acesso não autorizado, hackers cibernéticos e outras vulnerabilidades às quais um sistema conectado à Internet é suscetível. 	' } ,
  { term: ' 	30.  Confirmation (confirmação)	', definition: '	 Confirmação significa que uma transação foi processada pela rede e é altamente improvável ser revertida. Transações recebem uma confirmação quando são incluídas em um bloco e a cada bloco subsequente. Mesmo uma única confirmação pode ser considerada segura para transações de baixos valores, apesar de que, em valores maiores como US$ 1.000, faz sentido esperar por 6 confirmações ou mais. Cada confirmação reduz exponencialmente o risco de uma transação ser revertida. 	' } ,
  { term: ' 	31.  Core developers (Desenvolvedores principais)	', definition: '	 São os líderes do projeto. Propõem, avaliam e implementam melhorias, corrigem erros e estabelecem uma visão para o projeto, quando apropriado. 	' } ,
  { term: ' 	32.  Crypto/cripto	', definition: '	 Significa criptografada, oculta. Criptografia é o estudo de ocultar as coisas, a criptomoeda é a moeda criptografada. 	' } ,
  { term: ' 	33.  Criptografia	', definition: '	 A criptografia é o ramo da matemática que nos deixa criar provas matemáticas que fornecem um alto nível de segurança. Já sendo utilizada em comércio on-line e bancos. No caso do Bitcoin, a criptografia é utilizada para fazer com que seja impossível para qualquer um gastar fundos da carteira de outro usuário ou corromper a blockchain. Também pode ser utilizada para encriptar uma carteira, de modo que ela não pode ser utilizada sem uma senha. 	' } ,
  { term: ' 	34.  Crowdfunding (Financiamento coletivo)	', definition: '	 Consiste na obtenção de capital para financiar um determinado projeto de interesse coletivo, em geral com participação de pessoas físicas interessadas na iniciativa. 	' } ,
  { term: ' 	35.  Curva de Laffer	', definition: '	 É uma representação teórica que afirma que, se as taxas de impostos aumentam acima de um certo nível, as receitas fiscais podem realmente cair, porque as taxas de impostos mais altas desencorajam as pessoas a pagar. Da mesma forma, a Curva de Laffer afirma que o corte de impostos poderia, em teoria, levar a receitas fiscais maiores. 	' } ,
  { term: ' 	36.  DAO (Decentralized Autonomous Organization)	', definition: '	 É uma organização cujas regras são especificadas através de programas de computador conhecidos como contratos inteligentes, os quais são executados e validados por uma blockchain. 	' } ,
  { term: ' 	37.  Descentralizado	', definition: '	 Manter um conceito fora do controle de uma única entidade e fazer com que a população geral trabalhe em conjunto como fator de controle. 	' } ,
  { term: ' 	38.  Dissonância Cognitiva	', definition: '	 Segundo a Teoria da Dissonância Cognitiva de Leon Festinger (1957), ocorre o fenômeno quando um indivíduo possui opiniões ou comportamentos incompatíveis com suas crenças - havendo elementos cognitivos sem coerência. Exemplo simples vem de a “Raposa e as uvas” de Esopo, em que a Raposa, por desejar algo inatingível, passa a criticar o objeto de desejo para reduzir sua dissonância. 	' } ,
  { term: ' 	39.  Dividendo demográfico	', definition: '	" Período, normalmente entre 20 e 30 anos, durante o qual as taxas de fertilidade e mortalidade caem e as populações têm o crescimento anormal na produtividade econômica devido ao pico na proporção de pessoas em idade produtiva (no Brasil, estima-se que o ápice da razão de dependência ocorra entre 2019 e 2022). Inverno demográfico	 fenômeno percebido quando a taxa de natalidade se mantém em queda e a taxa de mortalidade mantém-se em níveis baixos. Isso tem como consequência o envelhecimento da população e a limitação das possibilidades de crescimento econômico. Segundo dados oficiais (IBGE), as projeções indicam taxas de fecundidade em quedas sucessivas (6,21 em 1960; 4,07 em 1980; 1,81 em 2012; 1,74 em 2014 e projeção de 1,69 para 2016). 	"	' } ,
  { term: ' 	40.  Dilema de Triffin (paradoxo de Triffin)	', definition: '	 É o conflito de interesses econômicos que surge entre os objetivos domésticos de curto prazo e os objetivos internacionais de longo prazo para países cujas moedas servem como moedas de reserva global. Esse dilema foi identificado na década de 1960 pelo economista belga-americano Robert Triffin, que apontou que o país cuja moeda é a moeda de reserva global, que as nações estrangeiras desejam manter, deve estar disposto a fornecer ao mundo um suprimento extra de sua moeda para atender à demanda mundial por essas reservas cambiais, levando a um déficit comercial. Para Robert Triffin, o sistema de Bretton Woods continha uma falha inerente e potencialmente fatal, ou seja, sua dependência em relação ao dólar, que deveria, conforme havia sido decidido em Bretton Woods, manter seu padrão-ouro. 	' } ,
  { term: ' 	41.  DYOR (Do Your Own Research)	', definition: '	 Significa “faça sua própria pesquisa” e é uma frase comum utilizada na internet para que os usuários não caiam em desinformação, a frase se tornou muito usada por entusiastas de criptomoedas. 	' } ,
  { term: ' 	42.  Early adopter	', definition: '	 Alguém que é uma das primeiras pessoas a começar a usar um novo produto, especialmente uma nova peça de tecnologia. 	' } ,
  { term: ' 	43.  Empréstimo Colateralizado	', definition: '	 É um ativo que é dado como garantia de pagamento para uma obrigação de dívida. Por exemplo, no caso de uma hipoteca, o imóvel serve como colateral do empréstimo e, no mercado de criptomoeda, deixa uma quantia em crypto como garantia. Desta forma, o banco ou plataforma crypto possui uma garantia em caso de não cumprimento do devedor. 	' } ,
  { term: ' 	44.  Efeito Cantillon	', definition: '	 Os primeiros a receber o dinheiro recém-criado por um Banco Central veem sua renda subir, enquanto os últimos a receber o dinheiro veem seu poder de compra declinar. 	' } ,
  { term: ' 	45.  Efeito Dunning-Kruger	', definition: '	 Explica por que pessoas de baixo QI e conhecimento se sentem confiantes e capazes de emitir opiniões, viés cognitivo de ilusória superioridade. 	' } ,
  { term: ' 	46.  Efeito Rede	', definition: '	 É um fenômeno pelo qual um número crescente de pessoas ou participantes melhora o valor de um bem ou serviço. A Internet é um exemplo do efeito de rede. Inicialmente, havia poucos usuários na Internet, uma vez que era de pouco valor para qualquer pessoa fora do exército e para alguns pesquisadores. No entanto, à medida que mais usuários obtinham acesso à Internet, eles produziam mais conteúdo, informações e serviços. O desenvolvimento e aprimoramento de sites atraíram mais usuários para se conectarem e negociarem entre si. À medida que a Internet experimentava aumento no tráfego, ela oferecia mais valor, levando a um efeito de rede. 	' } ,
  { term: ' 	47.  Efeito Lindy	', definition: '	 É o conceito de que o futuro da expectativa de vida de algumas coisas não perecíveis, como uma tecnologia ou uma ideia, é proporcional à sua idade atual, de modo que cada período adicional de sobrevivência implica uma maior expectativa de vida restante. Logo, quanto mais antigo algo for, mais tempo provavelmente existirá no futuro. De acordo com o Efeito Lindy, como o bitcoin existe há cerca de 10 anos, podemos esperar que ele continue por mais 10 anos. A cada ano a mais que ele sobrevive, mais tempo podemos esperar que ele esteja por aí no futuro. Como Taleb nos diz, a robustez de algo é proporcional à sua vida. Quanto mais tempo sobrevive, maior é a probabilidade de continuar a sobreviver. 	' } ,
  { term: ' 	48.  Endereços	', definition: '	" Equivalente à conta de um banco, informação necessária para envio de bitcoin, derivado da chave pública. Existem 3 tipos de endereços no Bitcoin Bech32 (Segwit Nativo) que começam com bc1. Ex.	 bc1qar0srrr7xfkvy998745ydnw9an59gtzzwf9mdq. Situação	 Compatível somente com carteiras que aceitam segwit. Dessa forma, uma carteira antiga pode não reconhecer fundos enviados a partir desse endereço. Obs.	 Oferece as menores taxas possíveis. Endereços	 P2SH (Pay-to-Script-Hash, Segwit). Início	 Começam com 3. Ex.	 3K965KmP1Z73CnmQviecrnyiWrnqRhWXuA. Situação	 Endereço de transição	 Melhor opção para a maior parte dos usuários por ser compatível com todas as wallets. Obs.	 Baixas taxas de transação. Endereços	 P2PKH Legacy (Pay-to-PubkeyHash, não segwit). Início	 Começam com 1. Ex.	 1OvyeornyiWrnqRhWXuAK965KmP1Z73CNm. Situação	 Endereço antigo	 Endereço compatível com todas as wallets.					"	' } ,
  { term: ' 	49.  Exchanges (corretoras)	', definition: '	 Uma “corretora” de criptomoedas, ou uma troca de moeda digital, é uma empresa que permite aos clientes negociarem criptomoedas ou moedas digitais por outros ativos, como moeda fiduciária convencional ou outras moedas digitais. 	' } ,
  { term: ' 	50.  Equity tokens (token de patrimônio)	', definition: '	" Os equity tokens funcionam mais como um ativo de stock asset. Em outras palavras, os detentores de tokens de patrimônio possuem alguma forma de propriedade em seus investimentos. Seus tokens representam quanta porcentagem de propriedade eles realmente possuem. Na maioria dos casos, os tokens de patrimônio representam um ativo, propriedade ou empreendimento de terceiros. Os equity tokens vêm em muitas formas	 Stocks, Contratos Futuros, Opções, Tokenized Real Estate e Tokenized Ventures. 	"	' } ,
  { term: ' 	51.  Efeito Gell-Mann	', definition: '	 Em um discurso em 2002, Crichton cunhou o termo efeito da amnésia de Gell-Mann. Ele usou esse termo para descrever o fenômeno de especialistas acreditarem em artigos de notícias sobre tópicos fora de suas áreas de especialização, mesmo depois de reconhecerem que artigos dentro de suas áreas de especialização escritos na mesma publicação estão cheios de erros e mal-entendidos. Ele explica a ironia do termo dizendo que surgiu "porque uma vez eu discuti isso com Murray Gell-Mann, e ao mencionar um nome famoso, dou maior importância a mim mesmo e ao efeito do que o faria de outra forma." 	' } ,
  { term: ' 	52.  Faucets (Torneiras)	', definition: '	 Uma torneira de bitcoin é um sistema de recompensa, na forma de um site ou aplicativo, que distribui recompensas na forma de um satoshi, que é um centésimo de um milionésimo de BTC, para os visitantes reivindicarem em troca de concluir um captcha ou tarefa, conforme descrito pelo site. 	' } ,
  { term: ' 	53.  Fork (soft fork e hard fork)	', definition: '	 Fork é uma ramificação de uma rede de moedas, pode ser uma atualização ou nova versão. Se for retrocompatível, é soft fork; se não for retrocompatível, é hard fork – como os forks que resultaram no bitcoin cash, bitcoin gold e demais novas moedas que reconheceram blocos do bitcoin até certo ponto rodando seu próprio cliente incompatível (com suas próprias regras) depois. 	' } ,
  { term: ' 	54.  Fees	', definition: '	 O valor pago a um minerador para incluir uma transação em um bloco. 	' } ,
  { term: ' 	55.  Gasto duplo	', definition: '	 É uma possível causa de falha de sistemas de criptomoedas. O gasto duplo acontece quando um usuário consegue gastar as mesmas moedas digitais mais de uma vez. Diferentemente de moedas físicas, arquivos digitais podem ser duplicados, logo, o ato de gastar uma moeda digital não implica uma transferência de posse da mesma para outra pessoa. Portanto, é necessário que outros meios sejam utilizados para prevenção contra o gasto duplo. 	' } ,
  { term: ' 	56.  Generais Bizantinos	', definition: '	 Em computação, o Problema dos Dois Generais é um experimento mental para ilustrar as armadilhas e desafios de planejamento na tentativa de coordenar uma ação através da comunicação sobre um ato não confiável. 	' } ,
  { term: ' 	57.  Gold Standard (padrão-ouro)	', definition: '	 É um sistema monetário no qual a unidade de conta econômica padrão é baseada em uma quantidade fixa de ouro. O padrão-ouro foi amplamente utilizado no século XIX e no início do século XX. A maioria das nações abandonou o padrão-ouro como base de seus sistemas monetários durante o século XX, embora muitos ainda mantenham reservas de ouro substanciais. 	' } ,
  { term: ' 	58.  Geração nem-nem	', definition: '	 O termo refere-se à população jovem fora do mercado de trabalho e de instituições educacionais. 	' } ,
  { term: ' 	59.  Halving (halvening)	', definition: '	 É um ajuste que ocorre na rede do Bitcoin e que reduz pela metade a recompensa dos mineradores, o que tem como consequência um corte na oferta de novas criptomoedas. E isso garante a característica deflacionária deste ativo. 	' } ,
  { term: ' 	60.  Hash/hashing	', definition: '	 Também conhecido como ID da transação ou txID, é um identificador único que pode ser usado em qualquer explorador de blocos para buscar por detalhes públicos de uma transação específica. Toda transação feita on-chain tem um hash único composto por vários caracteres alfanuméricos. Todo hash é único e derivado das informações da transação. Uma função hash, como as funções hash usadas para criar os diferentes tipos de endereços, é um algoritmo que mapeia dados de comprimento variável e os converte em dados de comprimento fixo. Os valores retornados por uma função hash são chamados de hashes e eles servem para compactar dados e assegurar a integridade dos dados transmitidos. 	' } ,
  { term: ' 	61.  Hashrate (taxa de hash)	', definition: '	 A taxa de hash é a unidade de medida do poder de processamento da rede Bitcoin. A rede Bitcoin deve fazer operações matemáticas intensivas para fins de segurança. Quando a rede atinge uma taxa de hash de 10 Th/s, significa que ela pode processar 10 trilhões de cálculos por segundo. 	' } ,
  { term: ' 	62.  Hash	', definition: '	 Uma função que mapeia dados de comprimento variável em dados de tamanho fixo. Usado para identificar transações, blocos, calcular endereços e minerar blocos. 	' } ,
  { term: ' 	63.  Hodl (holdlers)	', definition: '	 Um erro de escrita cometido por um usuário do pioneiro fórum Bitcointalk durante a bull run de 2013, que escreveu a palavra Holding (segurar) de forma errada, Hodling. Surgiu então o verbo "to hodl". Hodler é uma pessoa que não vende e segura seus bitcoins independente se o preço subir ou cair. 	' } ,
  { term: ' 	64.  Hedge (Cobertura)	', definition: '	 É uma estratégia de proteção para os riscos de um investimento, que neutraliza a posição comprada ou vendida contra o risco de grandes variações de preço de um determinado ativo. Ao fazer uma operação de hedging, o investidor tem como objetivo eliminar a possibilidade de perdas futuras. 	' } ,
  { term: ' 	65.  Hard money	', definition: '	 Moeda forte, moeda com boa cotação cambial. 	' } ,
  { term: ' 	66.  Hardware Wallet	', definition: '	 Um dispositivo relativamente seguro e prático (como Ledger, Keepkey e Trezor) para armazenar e assinar transações, protegendo as chaves privadas de transações. 	' } ,
  { term: ' 	67.  Hiperbitcoinização	', definition: '	" Esse fenômeno pode ser mais observado primeiramente em economias emergentes e subdesenvolvidas. O bitcoin se torna(rá) um refúgio seguro frente aos descompassos do Estado que causa crises financeiras	 colapso das moedas nacionais, hiperinflação, colapso das dívidas nacionais. 	"	' } ,
  { term: ' 	68.  HFSP (Have fun staying poor)	', definition: '	 A frase significa “Divirta-se ficando pobre. Frase que virou um “meme” como uma resposta a alguém que acabou de vender bitcoin ou disse que nunca consideraria comprar bitcoin. 	' } ,
  { term: ' 	69.  ICO (Initial coin offering)	', definition: '	 Uma oferta inicial de moedas (ICO) é o equivalente do setor de criptomoedas a uma oferta pública inicial (IPO). As ICOs funcionam como uma maneira de arrecadar fundos, em que uma empresa que busca arrecadar dinheiro para criar uma nova moeda, aplicativo ou serviço lança uma ICO. Os investidores interessados podem comprar a oferta e receber um novo token de criptomoeda emitido pela empresa. Esse token pode ter alguma utilidade no uso do produto ou serviço que a empresa está oferecendo ou pode representar apenas uma participação na empresa ou no projeto. 	' } ,
  { term: ' 	70.  IOUs (“I owe you”)	', definition: '	 É geralmente um documento informal que reconhece uma dívida. Um IOU difere de uma nota promissória, pois um IOU não é um instrumento negociável e não especifica termos de reembolso, como o horário do reembolso. Os IOUs geralmente especificam o devedor, o valor devido e, às vezes, o credor. 	' } ,
  { term: ' 	71.  Impersonificação	', definition: '	 Deixar de possuir qualidades, características ou aspectos de pessoa; fazer com que alguém ou si mesmo deixe de possuir qualidades pessoais. Etimologia (origem da palavra impersonificar). Im + personificar. (Dicionário on-line de Português). 	' } ,
  { term: ' 	72.  KYC ("know your customer")	', definition: '	 política financeira de exigir identificação do cliente, apresentação de documentos e até com reconhecimento facial, de voz e de digitais. 	' } ,
  { term: ' 	73.  Lei de Gresham	', definition: '	" A Lei de Gresham resume-se na seguinte oração	 É um princípio econômico que diz que uma moeda sobrevalorizada (tem um valor determinado por uma autoridade monetária acima do de mercado) expulsa uma moeda subvalorizada (tem um valor determinado pela mesma autoridade abaixo do de mercado). Por exemplo, nos padrões bimetálicos, a prata circulava mais e o ouro era mais entesourado; ou, como hoje na Venezuela, em que os bolívares têm alta velocidade e os dólares são guardados como reserva de valor. 	"	' } ,
  { term: ' 	74.  Lei de Amara	', definition: '	 O cientista Roy Charles Amara definiu uma regra que encoraja todos a pensar um pouco mais sobre a tecnologia. A lei diz que “Tendemos a superestimar o efeito de uma tecnologia no curto prazo e a subestimar seu efeito no longo prazo”. Ou seja, temos a tendência de ficar extremamente entusiasmados com as novas tecnologias e nossas expectativas inicialmente superam a realidade. Porém, eventualmente, essa dinâmica muda e começamos a subestimar o impacto que uma tecnologia terá. 	' } ,
  { term: ' 	75.  Lei de Metcalfe	', definition: '	 A lei de Metcalfe afirma que o efeito de uma rede é proporcional ao quadrado do número de usuários conectados no sistema (n²). A lei caracteriza muitos dos efeitos de rede de tecnologias de comunicação e redes como a Internet, redes sociais e a World Wide Web e também a rede Bitcoin (com base no número de usuários ativos). 	' } ,
  { term: ' 	76.  Lei de Wagner	', definition: '	" Também conhecida como a lei do aumento da despesa do Estado. A lei de Wagner sugere que um Estado Social evolui de capitalismo de livre mercado, devido ao fato de a população exigir cada vez maiores serviços sociais. Os neokeynesianos e os socialistas muitas vezes exortam os governos a imitar Estados de Bem-Estar modernos, como a Suécia. A despesa pública aumenta constantemente, mostrando uma tendência ascendente. Tal lei prevê que o desenvolvimento de uma economia industrial será acompanhada por um aumento da percentagem da despesa pública no Produto Interno Bruto	 “O advento da sociedade industrial moderna resultará no aumento da pressão política para o progresso social e aumento da provisão para créditos de consideração social pela indústria.” 	"	' } ,
  { term: ' 	77.  Lei de Michels ou Lei da Oligarquia	', definition: '	 afirma que democracia e organização de grande escala são incompatíveis, confirmando a falsidade da "Teoria do interesse público". 	' } ,
  { term: ' 	78.  Lei de Moore	', definition: '	 É uma observação e projeção de uma tendência histórica relacionada à indústria de microchips e processamento de computadores. Foi observada por Gordon E. Moore, e consiste na previsão de que o número de transistores dos chips teria um aumento de 100%, pelo mesmo custo, a cada período de 18 meses. 	' } ,
  { term: ' 	79.  Lei de Gall (Gall\'s Law)	', definition: '	" \"Um sistema complexo que funciona invariavelmente evoluiu de um sistema simples que funcionava. A proposição inversa também parece ser verdadeira	 um sistema complexo projetado do zero nunca funciona e não pode ser feito para funcionar. Você tem que começar de novo, começando com um sistema simples de trabalho.\" John Gall Outra lei que o Bitcoin respeita é a Gall\'s Law. O Bitcoin é muito simples. Ele minimiza o número de variáveis dinâmicas. Novos sistemas complexos são incrivelmente difíceis de projetar do zero. Um processo é bom quando não se trata de construir sistemas complexos do zero. Comece com um sistema simples que funcione e aprimore-o. Como alternativa, pegue um conjunto de subsistemas que estão funcionando (pequenos) e os componha, mas certifique-se de que a composição em si não se torne complexa, pois isso também não funcionará. Desenvolva iterativamente em pequenos passos e frequentemente certifique-se de que o resultado ainda está funcionando. 	"	' } ,
  { term: ' 	80.  Legacy System (sistema legado)	', definition: '	 O termo “sistema legado” descreve um sistema antigo que permanece em operação em uma organização. 	' } ,
  { term: ' 	81.  Long e Short	', definition: '	 É uma estratégia que consiste em uma operação casada, na qual um investidor mantém uma posição vendida em um ativo (ação/criptomoeda) e comprada em outro no intuito de obter um residual financeiro da operação quando liquidá-la. Esta operação permite alavancagem financeira, pois é lastreada com margens de garantia. 	' } ,
  { term: ' 	82.  Lending / Marging lending (empréstimo)	', definition: '	 O empréstimo de criptomoeda é a situação em que os investidores podem usar seus ativos cripto como garantia para obter um empréstimo fiduciário ou stablecoin, enquanto os credores fornecem os ativos necessários para o empréstimo a uma taxa de juros acordada. 	' } ,
  { term: ' 	83.  Mineração	', definition: '	 é o processo de utilização de computadores para realizar cálculos matemáticos para confirmar as transações da rede Bitcoin e aumentar a segurança. Como recompensa por seus serviços, os mineradores de bitcoin podem receber as taxas das transações confirmadas, além de novas moedas criadas em cada bloco. A mineração é um mercado especializado e competitivo em que os benefícios são partilhados de acordo com o número de cálculos que são realizados. Nem todos os usuários bitcoin são mineradores e não é uma maneira fácil de ganhar dinheiro. 	' } ,
  { term: ' 	84.  Miner fee (Taxa de mineração) / Trasaction fee (Taxa de transação)	', definition: '	 São pequenas quantidades de bitcoin concedidas para incentivar os mineradores de bitcoin a confirmar transações de bitcoin. Os mineradores de bitcoin são peças importantes que confirmam e protegem as transações na rede de Bitcoin. As taxas dos mineradores pagam aos mineradores pelo serviço que prestam. 	' } ,
  { term: ' 	85.  Mempool	', definition: '	 O grupo de transações esperando para serem incluídas em um bloco por um minerador. 	' } ,
  { term: ' 	86.  Mercado futuros	', definition: '	 Um contrato de futuros é um acordo legal para comprar ou vender um determinado ativo sendo ele commodity ou título a um preço predeterminado em um momento específico no futuro. 	' } ,
  { term: ' 	87.  Multisig	', definition: '	 A assinatura múltipla é uma configuração de carteira que pode exigir mais de uma chave privada para autorizar uma transação. 	' } ,
  { term: ' 	88.  Moeda fiduciária (Fiat)	', definition: '	 É a moeda legal de qualquer país em que é impressa e emitida pelo governo via Banco Central. Moeda fiduciária é qualquer título não conversível, ou seja, não é lastreada a nenhum metal (ouro, prata) e não tem nenhum valor “intrínseco”. Seu valor advém da confiança que as pessoas têm em quem emitiu o título. 	' } ,
  { term: ' 	89.  Monerização	', definition: '	 monerizar é aumentar fungibilidade e privacidade (do token ou da rede), saldos de bitcoin na liquid/lightning seriam “monerizados”, ou o próprio Bitcoin estaria se aproximando aos atributos do monero ao adotar Taproot e outras melhorias de fungibilidade e privacidade. 	' } ,
  { term: ' 	90.  Network computer (Rede de computadores)	', definition: '	 Ou Rede de dados, na informática e na telecomunicação é um conjunto de dois ou mais dispositivos eletrônicos de computação (ou módulos processadores ou nós da rede) interligados por um sistema de comunicação digital (ou link de dados), guiados por um conjunto de regras (protocolo de rede) para compartilhar entre si informação, serviços e, recursos físicos e lógicos. 	' } ,
  { term: ' 	91.  Node (nó)	', definition: '	" Um node é um participante ativo e soberano da rede P2P do Bitcoin. Existem dois tipos de node	 full node (nó completo), um nó que carrega uma cópia completa da blockchain, e pruned node (nó cortado), um nó que tem apenas os últimos blocos da rede bitcoin. Ambos os nodes validam transações e propagam as transações pela rede, além de ter mempool. A única diferença é que o nó pruned não tem os blocos mais antigos da rede para ajudar na sincronização inicial dos blocos por novos nós entrando na rede. 	"	' } ,
  { term: ' 	92.  Noob/newbie	', definition: '	 calouro, iniciante. 	' } ,
  { term: ' 	93.  NGU (Number go Up) Technology	', definition: '	" Foi cunhado pelo famoso bitcoiner Pierre Rochard no twitter	 “Bitcoin é a tecnologia NGU mais avançada do mundo.” Isso quer dizer que os recém-chegados elevam a quantidade de usuários utilizando a rede bitcoin, ao passo que o preço do ativo também aumenta. A tecnologia Number Go Up expandido a sua abordagem também se refere a extrema escassez do bitcoin e a incapacidade de copiar seu efeito rede, isso resulta no aumento do preço do Bitcoin ao passo que outros atributos também aumentam como	 quantidade de nós Bitcoin ativos; Hashpower; colaborações dos desenvolvedores; empresas provendo produtos e serviços; empregos gerados em todo ecossistema Bitcoin; números de transações; cobertura da mídia e FOMO; financiamento em projetos e desenvolvimento do Bitcoin. "	' } ,
  { term: ' 	94.  Open source	', definition: '	 Software de código aberto é aquele em que o códigofonte é disponibilizado e licenciado com uma licença de código aberto na qual o direito autoral fornece o direito de estudar, modificar e distribuir o software de graça para qualquer um e para qualquer finalidade. 	' } ,
  { term: ' 	95.  On-chain (dentro da cadeia)	', definition: '	 As transações dentro da cadeia referem-se às transações de criptomoeda que ocorrem na blockchain - isto é, nos registros do blockchain, e permanecem dependentes do Estado da blockchain para sua validade. Todas essas transações em cadeia ocorrem e são consideradas válidas apenas quando da blockchain é modificado para refletir essas transações nos registros/livro de razão público. 	' } ,
  { term: ' 	96.  Off-chain (fora da cadeia)	', definition: '	 As transações fora da cadeia referem-se às transações que ocorrem em uma rede de criptomoedas que movem o valor para fora da blockchain. Devido ao seu custo zero/baixo, liquidação imediata e maior anonimato, as transações fora da rede estão ganhando popularidade, especialmente entre grandes exchanges. 	' } ,
  { term: ' 	97.  OTC – Over The Counter (Mercado Balcão)	', definition: '	 É a situação em que investidores profissionais, fundos, empresas e pessoas compram e vendem um ativo em grandes quantidades fora da Exchange. 	' } ,
  { term: ' 	98.  P2P (Peer-to-peer)	', definition: '	 É uma arquitetura de redes de computadores em que cada um dos pontos ou nós da rede funciona tanto como cliente quanto como servidor, permitindo compartilhamentos de serviços e dados sem a necessidade de um servidor central. No caso do Bitcoin, a rede é construída de modo que cada utilizador transmita as transações de outros. 	' } ,
  { term: ' 	99.  Pirâmides / Ponzi Scheme (esquema Ponzi)	', definition: '	 É um esquema com operação fraudulenta sofisticada de investimento do tipo esquema em pirâmide que envolve a promessa de pagamento de rendimentos anormalmente altos aos investidores à custa do dinheiro pago pelos investidores que chegarem posteriormente, em vez da receita gerada por qualquer negócio real. No Brasil, até a participação é criminalizada desde a Lei 1.521/51, art. 2, IX (pichardismo e equivalentes). 	' } ,
  { term: ' 	100.  Profecia autorrealizável	', definition: '	 Prognóstico que provoca sua própria concretização. Previsão que influencia o comportamento das pessoas de modo que acaba se realizando. Conceito de Robert Merton (1949). Muitas vezes é causado pelo “efeito manada”, quando grupos se comportam de maneira semelhante sem organização planejada, seguindo o padrão da “massa crítica” - número mínimo de adotantes para sustentar ação. 	' } ,
  { term: ' 	101.  Proof of Brain (prova de cérebro)	', definition: '	 medida de quanto de inteligência há em um ambiente ou projeto, aferida pela qualidade dos envolvidos e número e qualidade das contribuições nos repositórios. 	' } ,
  { term: ' 	102.  PoW (Proof of Work)	', definition: '	 Refere-se a uma porção dos dados que é difícil (consome muitos recursos e tempo) de ser produzida e extremamente fácil de verificar se atende alguns requisitos predeterminados. Produzir prova de trabalho pode ser um processo aleatório com baixa probabilidade de acerto, para que muita tentativa e erro (força bruta) seja requerida em média antes que uma prova seja gerada. 	' } ,
  { term: ' 	103.  PoS (Proof of Stake)	', definition: '	 Prova de participação, normalmente com saldo vinculado ao nó. 	' } ,
  { term: ' 	104.  Pump and dump	', definition: '	 É um esquema de manipulação que envolve o aumento artificial do preço de um ativo por meio de declarações positivas falsas e enganosas (muitas vezes através de grupos do telegram ou relatórios de investimento), a fim de vender o ativo por preço mais alto (e algumas vezes recomprar depois de divulgação de notícias negativas, igualmente falsas ou fabricadas). 	' } ,
  { term: ' 	105.  Preferência temporal	', definition: '	 A preferência temporal é uma teoria em economia que trata a respeito da escolha de investimento e consumo de bens em relação ao tempo. Os indivíduos estão sujeitos à passagem do tempo. Suas existências são finitas, seus corpos e mentes decaem. O tempo, portanto, é um fator escasso e, como tal, os indivíduos precisam economizálo. 	' } ,
  { term: ' 	106.  Baixa preferência	', definition: '	 Quando você possui visão de longo prazo. Ao não desfrutar de um bem no presente, a pessoa está disposta a algum sacrifício (poupar é sempre um ato de sacrifício) para adiar o usufruto desses bens no presente. Por isso, ao consumir pouco, a pessoa tem a preferência temporal baixa, nisso se permite que haja mais bens disponíveis para ser emprestados e aplicados em processos de investimento. Uma preferência temporal baixa gera uma maior abundância de bens livres para ser emprestados. 	' } ,
  { term: ' 	107.  Alta preferência	', definition: '	 Quando a pessoa possui visão de curto prazo. A pessoa se torna uma consumista, voltada sempre ao tempo presente e avessa à poupança. A escassez de capital é a consequência natural da alta preferência temporal das pessoas, traduzindo-se em um alto preço (juros) cobrado pelo uso do pouco capital que ainda resta. 	' } ,
  { term: ' 	108.  Ponerologia Política	', definition: '	 É o estudo do mal, do grego poneros (malícia, maldade), é a ciência da natureza do mal adaptada a propósitos políticos. O termo foi cunhado pelo psiquiatra polonês Andrzej M. Lobaczewski, que estudou como os psicopatas influenciam no avanço da injustiça e como abrem caminho para o poder na política. 	' } ,
  { term: ' 	109.  Problema de Olson (A Lógica da Ação Coletiva)	', definition: '	 A tese básica deste livro é a de que "mesmo que todos os indivíduos de um grupo grande sejam racionais e centrados em seus próprios interesses, e que saiam ganhando se, como grupo, agirem para atingir seus objetivos comuns, ainda assim eles não agirão voluntariamente para promover esses interesses comuns e grupais" (Olson, 1999, p. 14). 	' } ,
  { term: ' 	110.  Paper wallet	', definition: '	 Uma carteira off-line de armazenamento frio (cold storage), em que a chave privada é impressa em um pedaço de papel para armazenamento off-line. Era considerada uma das maneiras mais seguras de armazenar chaves privadas antes da criação de soluções de hardware e da implementação do backup a partir de seed (mnemônicos). 	' } ,
  { term: ' 	111.  Quantitative easing (alívios quantitativos)	', definition: '	 A flexibilização quantitativa (QE) é uma forma de política monetária não convencional, na qual um Banco Central compra títulos de longo prazo no mercado aberto, a fim de aumentar a oferta de moeda e incentivar empréstimos e investimentos. A compra desses títulos acrescenta mais dinheiro à economia e também serve para diminuir as taxas de juros, oferecendo títulos de renda fixa. Também expande o balanço do Banco Central. Quando as taxas de juros de curto prazo são iguais ou próximas a zero, as operações normais de mercado aberto de um banco central, que têm como alvo as taxas de juros, não são mais eficazes. Em vez disso, um Banco Central pode direcionar quantidades especificadas de ativos para compra. A flexibilização quantitativa aumenta a oferta de dinheiro comprando ativos com reservas bancárias recém-criadas, a fim de fornecer mais liquidez aos bancos. 	' } ,
  { term: ' 	112.  Saylorização	', definition: '	 processo de empresas abertas usarem juro negativo para comprarem bitcoin alavancado em vez de fazer recompra de ações, em processo de ataque especulativo contra fiats, fazendo até mesmo investidores de índices como SP500 se expor marginalmente a bitcoin. 	' } ,
  { term: ' 	113.  Smart contracts (contratos inteligentes)	', definition: '	 É um contrato de execução automática com os termos do contrato entre comprador e vendedor sendo gravados diretamente em linhas de código. O código e os acordos nele contidos existem em uma rede blockchain descentralizada e distribuída. O código controla a execução e as transações são rastreáveis e irreversíveis. Os contratos inteligentes permitem que transações e acordos confiáveis sejam realizados entre partes anônimas e díspares, sem a necessidade de uma autoridade central, sistema legal ou mecanismo de execução externo. Embora a tecnologia blockchain venha a ser pensada principalmente como a base do bitcoin, ela evoluiu muito além de sustentar uma criptomoeda. 	' } ,
  { term: ' 	114.  Slippage	', definition: '	 Refere-se à diferença entre o preço esperado de uma negociação e o preço pelo qual a negociação é executada. A derrapagem pode ocorrer a qualquer momento, mas é mais prevalente durante os períodos de maior volatilidade quando as ordens de mercado são usadas. Também pode ocorrer quando uma grande ordem é executada, mas não há volume suficiente no preço escolhido para manter o spread de compra / venda atual. 	' } ,
  { term: ' 	115.  Satoshi/sats	', definition: '	 A menor unidade divisível de um bitcoin. Cada unidade de bitcoin é composta de 100 milhões de satoshis (8 casas decimais). 1 satoshi (1 sat) = 0,00000001 bitcoin / 1 bitcoin = 100.000.000 de sats. 	' } ,
  { term: ' 	116.  Scam	', definition: '	 É um esquema fraudulento armado intencionalmente para enganar uma pessoa ou grupo de pessoas com objetivo de roubar dinheiro. 	' } ,
  { term: ' 	117.  Shitcoins	', definition: '	 É um termo pejorativo usado para descrever uma criptomoeda que se tornou inútil. É uma criptomoeda sem propósito, valor ou futuro. 	' } ,
  { term: ' 	118.  Shitcoinheiro	', definition: '	" Indivíduos que, por ignorância ou malícia, acumulam e/ou promovem tokens digitais sem valor. Muitos shitcoinheiros carecem de conhecimento nas áreas da economia austríaca, modelos de camadas de escala de protocolo, teoria dos jogos e ética. Muitos são propensos a explosões emocionais quando expostos à razão ou a perguntas difíceis sobre seus portfólios diversificados. Os passatempos incluem divertir-se se mantendo pobre e criar definições para maximalistas de Bitcoin no Urban Dictionary. Steve ignorou o Bitcoin por anos e sente que perdeu o barco, apesar de seus amigos bitcoinheiros tentarem fazer com que ele acumulasse sats repetidamente. Para recuperar o tempo perdido, ele pulou na Coinbase e comprou todas as moedas de baixa capitalização na esperança de que um dia fosse o ""próximo"" Bitcoin. Steve é um cretino total. (By	 BTC Sessions August 16, 2021). 	"	' } ,
  { term: ' 	119.  Sound money (Dinheiro sonante)	', definition: '	 É aquele que não está sujeito a apreciação ou depreciação repentina do poder de compra no longo prazo, auxiliado por mecanismos de autocorreção inerentes a um sistema de livre mercado. 	' } ,
  { term: ' 	120.  Stablecoins	', definition: '	 É uma classe de criptomoedas que tenta oferecer estabilidade de preços e é garantida por um ativo de reserva (dólar, euro, ouro etc.). Os Stablecoins ganharam força ao tentar oferecer o melhor dos dois mundos, o processamento instantâneo e a segurança ou privacidade dos pagamentos de criptomoedas e as avaliações estáveis sem volatilidade de moedas fiduciárias. 	' } ,
  { term: ' 	121.  Teoria das Escolhas Públicas	', definition: '	 A escolha pública ou Teoria da Escolha Pública é um ramo da teoria econômica em que os conceitos da economia de mercado são aplicados à política e aos serviços públicos. Assim, na ciência política, a escolha pública critica a visão romântica de que o político é um servidor altruísta do interesse público em geral, substituindo-a por uma abordagem mais consentânea com o comportamento humano. Em vez de conceder aos políticos um tratamento especial, a escolha pública os trata como meros agentes humanos que priorizam a satisfação do seu próprio interesse. 	' } ,
  { term: ' 	122.  Testnet	', definition: '	 É uma rede separada com um design quase idêntico ao da rede Bitcoin para que os desenvolvedores possam testar melhorias e inovações sem colocar satoshis de verdade em risco. 	' } ,
  { term: ' 	123.  UTXO	', definition: '	 Acrônimo de "Unspent Transaction Output" (saída de transação não gasta) é uma moeda de bitcoin que pode ser usado como input (entrada) para ser gasto em transações futuras. Basicamente, é como os bitcoins que você possui e pode gastar são chamados dentro da rede Bitcoin. O saldo de uma carteira Bitcoin, por exemplo, é a soma de UTXOs controladas pelas chaves privadas daquela carteira. 	' } ,
  { term: ' 	124.  xPub	', definition: '	 Significa “Extended Public Key” (chave pública estendida). As chaves xPub são úteis porque o Bitcoin emprega o conceito de saídas de transação não gastas (UTXOs) em endereços de retorno. É a chave que gera todos os endereços, assim, podem-se obter todos os dados da sua carteira, transações anteriores e futuras. Mesmo que signifique "chave pública estendida", esta chave deve permanecer privada e nunca ser compartilhada. 	' } ,
  { term: ' 	125.  Welfare State (Estado de bem-estar social)	', definition: '	" O Estado de bem-estar social, ou Estado-providência, ou Estado social, é um tipo de organização política, econômica e sociocultural que coloca o Estado como agente da promoção social e organizador da economia.					"	' } ,
  






  // ... adicione mais termos aqui
];

// Função para criar um elemento de termo
function createTermElement(term) {
  const termElement = document.createElement('div');
  termElement.classList.add('term');

  const termTitle = document.createElement('h3');
  termTitle.textContent = term.term;

  const termDefinition = document.createElement('p');
  termDefinition.textContent = term.definition;

  termElement.appendChild(termTitle);
  termElement.appendChild(termDefinition);

  return termElement;
}

// Função para filtrar e exibir os termos
function filterTerms() {
  const searchTerm = searchInput.value.toLowerCase();
  glossary.innerHTML = '';

  terms.forEach(term => {
    if (term.term.toLowerCase().includes(searchTerm)) {
      glossary.appendChild(createTermElement(term));
    }
  });
}

// Adiciona os termos iniciais ao glossário
terms.forEach(term => {
  glossary.appendChild(createTermElement(term));
});

// Escuta o evento de input no campo de pesquisa
searchInput.addEventListener('input', filterTerms);